# Service ID
rinnai_set_time:
  # If the service accepts entity IDs, target allows the user to specify entities by
  # entity, device, or area. If `target` is specified, `entity_id` should not be
  # defined in the `fields` map. By default it shows only targets matching entities
  # from the same domain as the service, but if further customization is required,
  # target supports the entity, device, and area selectors
  # (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector
  # parameters will automatically be applied to device and area, and device selector
  # parameters will automatically be applied to area. 
  target:
    entity:
      domain: climate
      integration: rinnaitouch
  # Different fields that your service accepts
  fields:
    # Key of the field
    set_datetime:
      # Whether or not field is required (default = false)
      required: false
      # Advanced fields are only shown when the advanced mode is enabled for the user
      # (default = false)
      advanced: false
      # Example value that can be passed for this field
      example: "2023-01-01T12:00:00+0000"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control
      # the input UI for this field
      selector:
        datetime:

set_schedule_period:
  target:
    entity:
      domain: climate
      integration: rinnaitouch
  fields:
    day:
      required: true
      selector:
        select:
          options:
            - label: Monday
              value: monday
            - label: Tuesday
              value: tuesday
            - label: Wednesday
              value: wednesday
            - label: Thursday
              value: thursday
            - label: Friday
              value: friday
            - label: Saturday
              value: saturday
            - label: Sunday
              value: sunday
            - label: Weekdays
              value: weekdays
            - label: Weekends
              value: weekends
            - label: All days
              value: all_days
    period:
      required: true
      selector:
        select:
          options:
            - label: Wake
              value: wake
            - label: Leave
              value: leave
            - label: Return
              value: return
            - label: Pre-Sleep
              value: pre_sleep
            - label: Sleep
              value: sleep
    start_time:
      required: true
      selector:
        time:
    temperature:
      required: true
      selector:
        number:
          min: 0
          max: 30
          step: 1
          mode: box
          unit_of_measurement: °C
    enabled_zones:
      required: false
      selector:
        select:
          multiple: true
          options:
            - label: Zone A
              value: A
            - label: Zone B
              value: B
            - label: Zone C
              value: C
            - label: Zone D
              value: D
